index.html, main.css
=> fix: adjust embed hight and margin

src/components/App.js
This PR prevents the app from calling the API on pause by replacing the `setTimeout()` with `setInterval()`. The interval ID returned from the function gets stored in the state when the audio is played. It will then be used in to clear the timer when user stops the player.
**Note:**
There is another `setTimeout` in the `catch` function. I decided to keep it there, since we currently don't have a mechanism to check if the player is paused by the user or due to failure in API call. Therefore, the `getNowPlaying` should still be called periodically in this case.
---
Closes https://github.com/freeCodeCamp/coderadio-client/issues/27
=> feat: Prevent API call on pause

src/components/Nav.js
=> navigation: open links in new tab - fixes #32

public/index.html
=> remove duplicate meta tags

src/assets/pause.svg, src/assets/play.svg, src/components/Footer.js, src/css/App.css
Please review.
TODO: check if we need to remove the SVG's from CDN.
=> Inline svg

package-lock.json, package.json, src/components/App.js, src/components/Main.js
this pr replaces ajax api calls with websocket.
closes #41
=> feat: add web socket

src/components/Visualizer.js
@ahmadabdolsaheb Please review.
=> support Safari - fixes #45

src/components/Main.js
Was looking through the code and noticed an unused toggleSidenav function in the Main component. This function is only used to toggle navOpen state in the Nav component so I cleaned it up to prevent confusion.
=> Remove unused toggleSidenav function in Main component

src/components/App.js, src/components/Footer.js
This pr will remove relays are default streams
=> fix: default to mounts

public/index.html
=> remove link tags for google plus

src/components/Main.js
- Turn `Main.js` to a functional component since the component doesn't use state
- Make the conditional rendering less repetitive
=> chore: clean up Main.js

src/components/Footer.js, src/components/Slider.js
- Make volume slider a standalone component
- Ref #29  
---
Btw, I'm thinking about making a renderless `SetVolume` component in a future PR. I don't have any approach for it yet, but moving this out of App.js would make the root component way cleaner.
=> chore: modularize volume slider

src/components/App.js
This allows to use shortcuts when visiting the page without having to
mage focus in the <App> component where there handlers are defined
=> Add keyboard shortuct handlers to main window

src/components/App.js
Reverts freeCodeCamp/coderadio-client#65
=> Revert "feat: default to remote streams"

src/components/Footer.js, src/components/PlayPauseButton.js
This is another attempt to modularize the app by making a stand-alone component for the play/pause button and move the logic for it out of the `Footer` component
Ref #29
=> chore: move play/pause button to its own component

src/components/App.js
Reverts freeCodeCamp/coderadio-client#68
=> Revert "Revert "feat: default to remote streams""

src/components/Nav.js, src/index.js
Hello everyone,
The main change in this PR is the conversion of the component to a functional component.
There are also some cleanups.
Please review :)
=> Refactor nav

src/components/Slider.js
In this PR the slider component is being converted into a functional component
Please review :)
=> Refactor Slider

src/components/App.js
Implemented a stop and resume functionality based on https://stackoverflow.com/questions/27258169/how-can-i-stop-and-resume-a-live-audio-stream-in-html5-instead-of-just-pausing-i
relatetd #80
=> feat: add stop/resume functionality 

README.md, package-lock.json, package.json, sample.env, src/components/App.js, src/index.js
This is a fairly standard Sentry setup.  It might help diagnose https://github.com/freeCodeCamp/coderadio-client/issues/80
=> feat: Sentry integration

src/components/App.js
Reverts freeCodeCamp/coderadio-client#73
=> Revert "Revert "Revert "feat: default to remote streams"""

src/components/App.js
Reverts freeCodeCamp/coderadio-client#99
revert X 4
=> Revert "Revert "Revert "Revert "feat: default to remote streams""""

package-lock.json, package.json, src/components/App.js
Hi! I've tried adding this feature before but didn't complete the requirements for it to be merged... Hope this time I get things right.
=> feat: Save user volume to local storage

src/components/App.js
The general idea here is to let the player communicate with React via `setState` rather than to directly query the player (if possible).
=> fix: zero volume errors

src/components/App.js
I found that the error handler isn't working properly due to the following condition
https://github.com/freeCodeCamp/coderadio-client/blob/4bfaa7ba8cc63d28b2aab18a5d39d014bfb733ab/src/components/App.js#L417-L428
With the player `src` being set to an empty string on `pause` (https://github.com/freeCodeCamp/coderadio-client/blob/master/src/components/App.js#L198), I believe we added this flag in the error handler to ensure the app doesn't falsely execute it when the user has paused the music (`this.state.playing` being `false`). However, the condition is also true when an error does occur, as the `playing` state is being `false` in this case as well, which causes the stream switching logic to not be run.
My fix is to add another condition, which is to check if the player source is truthy. …
=> fix: error handler

src/components/Footer.js
Hi,
This PR is for fixing the problem of album image not showing.
The album image is related to a props property (fastConnection) that is coming from the App component.
=> fix: fix album image not showing 

src/css/App.css
PR for fixing the footer issue problem
=> Fix footer image issue

.eslintrc-base.json, package-lock.json, package.json, src/components/App.js, src/components/CurrentSong.js, src/components/Footer.js, src/components/SongHistory.js, src/components/Visualizer.js, src/css/App.css
Hello my fellow FCCers, 
This is for https://github.com/freeCodeCamp/coderadio-client/issues/13. Basically, I have added a new component to the radio that displays the most recent songs that have been played provided by the FCC Radio API. 
This was achieved by just adding a new state on the main application called `songHistory` and passing that as props to the new component. Then we would just map out the response to the new component. 
Results: 
**For Desktop:**
**For Mobile: **
closes freeCodeCamp/freeCodeCamp/issues/41082
=> Recently Play History Implemented

cypress/integration/play-button.js
This PR is adding a test case for playing the music and checking that audio was effectively played.
It's related to the issue #41076
=> feat(tests): add test case for playing music

.github/workflows/cypress, .github/workflows/cypress.yml, package.json
=> add basic cypress workflow

src/components/App.js, src/components/Footer.js, src/components/PlayPauseButton.js, src/components/Slider.js, src/components/Visualizer.js
---
Hi 👋 I hope it's not the most useless pull request this project has received 😅 but the typos and broken comment formatting was bothering me everytime I open the project so I decided to fix that.
More precisely this is what I've done:
=> style: correct typos and comment formatting

public/index.html, src/components/Footer.js, src/components/SongHistory.js
Checklist:
Closes #XXXXX
Issue - https://github.com/freeCodeCamp/freeCodeCamp/issues/42236
=> fix: improved accessibility of SongHistory Button, Stream Selection 

src/components/Main.js, src/css/App.css
Reverts freeCodeCamp/coderadio-client#169
=> Revert "feat: add maintance banner"

.github/workflows/cypress.yml
=> chore: update Cypress to match Netlify's deploy OS

.github/workflows/ci.yml
Checklist:
Related to https://github.com/freeCodeCamp/freeCodeCamp/issues/41582
=> Feat(client): add lint job to ci pipeline

src/components/SongHistory.js, src/css/App.css
Checklist:
Closes #XXXXX
- Pulled song history list out of button and converted it to html list
- Added necessary aria attributes for disclosure button
- Updated CSS so list visibility is dependent on aria-hidden
- Updated individual song markup to be more screen reader friendly
I'm still not sure the song markup is as good as it can be. I will have to research this a little more. But the changes I have made so far are moving us in the right direction.
=> fix: song history accessibility

cypress/integration/play-button.js, package-lock.json, package.json, src/components/App.js, src/components/App.test.js, src/components/Footer.js, src/components/PlayPauseButton.js, src/css/App.css, src/utils/buildEventSource.js
=> feat: change api

src/components/App.js
Checklist:
This change is just to ensure we clean up everything before the App component unmounts.
=> fix: close sse before unmount

src/components/Main.js, src/css/App.css
=> feat: add maintenance banner

src/components/Footer.js, src/components/Visualizer.js
Checklist:
Ensures the timeout and interval are cleaned up before unmount.
=> fix: clear timeout on unmount

src/components/App.js
this pr tests the new installation uri's on the current client.
=> fix: adjust subscription parameters.

src/components/Main.js, src/css/App.css
Reverts freeCodeCamp/coderadio-client#303
=> Revert "feat: add maintenance banner"

public/index.html, src/css/App.css
=> feat: add widgetbot chat widget
