freeCodeCamp/coderadio-client

- src/components/Nav.js
Changes
```
https://learn.freecodecamp.org/
```
to
```
https://www.freecodecamp.org/learn/
```
---
I just noticed the incorrect link in the code, but I'm not sure if this fix is needed since user will get a 301 redirect anyway.
> fix: /learn url

- package-lock.json
- package.json
- src/components/App.js
This PR:
- Replaces `addEventListener` call with `react-hotkeys` library
- Moves the handlers of ArrowUp and ArrowDown keys to their own stand-alone function
- Closes #64 
**Note**: I use [GlobalHotKeys component](https://github.com/greena13/react-hotkeys#globalhotkeys-component) instead of `HotKeys` to achieve the behavior introduced in #58
> chore: use react-hotkeys to handle keyboard shortcuts

- src/components/App.js
- src/components/Footer.js
> feat: get stream based on bitrate and listeners

- src/components/PlayPauseButton.js
- Improves the accessibility of the app by using a `button` element for the play/pause button, instead of a `div` 
- Adds some CSS to override the default button styles
- Closes #71
> fix(a11y): make play/pause button more accessible

- src/components/App.js
I believe we initially made the app container focusable in order to have keyboard shortcuts working properly. Now that we have replaced manual keyboard event handling with `react-hotkeys`, there is no need to make the container focusable any more.
This PR cleans that up and resolves #74 in the process.
> chore: make the app container unfocusable

- src/components/App.js
This PR does some refactoring and most importantly, fixes #76 by correcting this line:
```js
const availableStreams = sortedStreams.filter(stream => stream.url !== url);
```
`availableStreams` above is assigned to the list of all streams, excluding the current one. This is not correct, however, as available streams should be all the streams we have, excluding current one **and** the ones in the errored list.
The app stops when it has tried all streams, and none is available.
> fix: avoid infinite loop in the onPlayerError function

- src/components/App.js
- src/components/Footer.js
Removes the `player` prop that is being passed to the Footer component, but isn't used.
> chore: remove unused prop

- src/components/Nav.js
Changes the order of navigation menu items, to make it consistent with the order on the main FCC page, and benefit those who navigate between FCC pages with muscle memory 😄 
Before
After
> chore: rearrange menu items

- src/components/App.js
This PR is an attempt to prevent #81 from happening again.
Quoted from [my comment](https://github.com/freeCodeCamp/coderadio-client/issues/81#issuecomment-654034487) in the issue thread:
> - OP lands on the page
> - The first stream URL they got had certificate issue (#79)
> - The page switches to a new stream and tries to play it
> - Since OP didn't interact with the page, the browser blocks the audio from playing
When user lands on the page, we make a websocket call to get all the stream URLs. The streams then get sorted and the first one in the list is set to the audio source. I'm not sure if this is true, but I guess the browser tries to load the media source (without actually playing it), and if it fails, it will call the `onError`.
In the error handling function, we do some logic …
> fix: prevent the app from autoplaying the music

- src/components/App.js
Signed-off-by: nhcarrigan <nhcarrigan@gmail.com>
Pulls the Sentry error logging out of the `onPlayerError` method - this was generating a lot of noise and resulting in 429 rate limits.
With this change, we should be able to re-enable the sentry setup on production and listen specifically for errors within the `NchanSubscriber` itself.
> fix: Revert sentry error logging

- public/index.html
- src/components/Nav.js
Signed-off-by: nhcarrigan <nhcarrigan@gmail.com>
This PR replaces the green favicons from the S3 instance with the indigo favicons from the CDN, and uses the CDN-hosted logo for the header.
@ahmadabdolsaheb I don't see a version of the coderadio meta image on the CDN. I used our standard 1920x1080 image, but if we want to maintain the existing unique image let me know. 🙂 
Closes #100
> fix: Replace favicons, use CDN logo

- src/components/App.js
I sometimes encounter the following error when toggling play/pause too fast. My fix for it is to add a condition to ensure `SUB.stop()` will not be called if the audio is already being paused.
(This screen can only be seen in local environment, but the error does get logged in the console in production)
> fix: prevent the SUB.stop() call if the audio is already paused

- public/index.html
Signed-off-by: nhcarrigan <nhcarrigan@gmail.com>
Adds the missing base favicon file, removes the unneeded 96x96 link.
> fix: Missed default favicon, remove extra size

- src/components/App.js
- src/components/PlayPauseButton.js
Essentially, the issue on mobile phones was due to a race condition where the event loop that tracked a user's initial page interaction hadn't resolved by the time `play()` was called. I fixed this by leveraging a new prop for `interacted`, which initialises as `false`. When a user clicks the play button, instead of immediately calling `play` I set a 200ms timeout (barely noticeable on the page) to allow that interaction to get logged, eliminating the erroneous "user has not interacted with the page" issue. In that timeout, the `interacted` flips to true and future play calls will run normally.
Closes #97
> fix: Android initial play error

- public/index.html
Signed-off-by: nhcarrigan <nhcarrigan@gmail.com>
With https://github.com/freeCodeCamp/cdn/pull/60 merged, we now have a dedicated code radio image in our CDN. This PR changes the meta links to use that image rather than the universal freeCodeCamp image.
> fix: Replace meta image

- src/components/App.js
- src/components/Slider.js
~~Hi, I've branched this out from #89 which is branched out from the latest master commit. I hope it's not a problem for you. In both cases, git will do a clean "fast-forward" merge without any conflicts.~~
The feature makes the slider more precise by increasing the range input's max value. I think it's nice when you want to set the volume "really low" without also lowering your system volume, which I find myself doing a lot.
> Increase slider max range

- src/components/App.js
- src/components/Footer.js
There is a typo in the onChange event of the footer dropdown, which is causing the selection to not be registered.
Also, the behavior of `setUrl` seems to be odd, in that the player stops completely when I select a stream. I found that this is due to the `playing` state not being updated (to `false`) at the time we execute the set URL logic (which needs `playing` to be `false`). Though I'm not sure why I didn't encounter the issue before
---
> fix: stream dropdown

- src/components/App.js
Our set stream function checks if `fastConnection` is either true or false, but its initial value can be `null`, therefore failing all the conditions for relays and fall back to use mount.
https://github.com/freeCodeCamp/coderadio-client/blob/9c45fb91382caec49ec759d0162c6658af1e9200/src/components/App.js#L368-L383
Fixes #120
> fix: use boolean for value of fastConnection

- package-lock.json
- package.json
- src/components/Main.js
- src/components/Visualizer.js
This PR:
- Is an attempt to reduce the CPU consumption by fixing a memory leak issue in the Visualizer component
- Related to #112
---
The issue can be reproduce by making the following changes to the code:
- Make the Main component render the Visualizer conditionally based on the `playing` state
- Add a console.log statement to [this line](https://github.com/freeCodeCamp/coderadio-client/blob/master/src/components/Visualizer.js#L88)
**Expected behavior:** When the user presses pause, the Visualizer component is unmounted, and there shouldn't be anything logged to the browser console.
**Actual behavior:** When the user presses pause, the Visualizer component is unmounted, and there are logs constantly printed in the browser console.
---
My fix for this is to move the recursion outside of …
> fix: prevent memory leak in Visualizer component

- src/css/App.css
Hi,
This PR is for making the background image responsive.
The animation is present for screens with width > 750 px
For screens with width < 750 px, I keep only the background image
For screens with width < 500 px, a blue background is displayed
I am open for any improvement
This PR is for the issue #105
> fix: Make background image responsive

- src/components/PlayPauseButton.js
- src/css/App.css
Checklist:
This PR is an attempt to fix the issue with the play button on mobile, specifically iOS devices. The fix is to convert the div that has `role="button"` to a `button` tag. 
I don't have an iOS device to test if my change addresses the issue, and could only ensure that there is no regression caused by the change.
Ref https://github.com/freeCodeCamp/freeCodeCamp/issues/41070
> fix: play button on mobile

- src/components/App.js
Checklist:
When the user clicks the pause button, we gradually fade the music down and only pause the player if the current volume is set to 0. 
A special thing about iOS devices is that they don't allow volume to be programmatically set, and the volume value is always 1. This means it will never get back to 0, thus never triggers the `pause` function.
> On the desktop, you can set and read the volume property of an <audio> or <video> element. This allows you to set the element’s audio volume relative to the computer’s current volume setting. A value of 1 plays sound at the normal level. A value of 0 silences the audio. Values between 0 and 1 attenuate the audio.
> 
> This volume adjustment can be useful, because it allows the user to mute a game, for example, while still listening to …
> fix: pause button on iOS devices

- src/components/Footer.js
Checklist:
Closes https://github.com/freeCodeCamp/freeCodeCamp/issues/43102
There were some typos in the function name in the Code Radio app:  stopCurrenttInterval and toggleIntterval.
I have changed stopCurrenttInterval to stopCurrentInterval, and toggleIntterval to toggleInterval .
Changes are made according to issue #43102.
> fix: typos in function name (stopCurrenttInterval and toggleIntterval) in footer.js

- cypress/integration/play-button.js
- package-lock.json
- package.json
- src/components/App.js
- src/components/Footer.js
- src/components/Main.js
- src/components/PlayPauseButton.js
- src/components/SongHistory.js
Checklist:
Closes https://github.com/freeCodeCamp/freeCodeCamp/issues/43098
It replaces the `react-hotkeys` dependency with native handling by listening to `keydown` events and the shortcuts are only available if the device is a browser (done by `react-device-detect` dependency).
Also fixed the bug when pressing space in a component that should relay on its own context instead of toggling play/pause. The solution was to create a disallow list to do not perform `tooglePlay` function if the focus is on components like Recent Song History.
> Remove react-hotkeys dependency in favor of native handling solution

- src/components/CurrentSong.js
Checklist:
Closes #XXXXX
The trouble with the progress bar is that most screen readers will continually announce intermittent updates on the current value of the bar, or emit a beep every few seconds to alert the user that progress is still being made, which can be quite annoying when you are trying to listen to the music. So I have removed the progress bar from the accessibility tree to solve this issue. The next step is to come up with an alternative method to allow AT users a way to see how much time is left on the current song.
> fix: hide progress bar from accessibility tree

- src/components/App.js
- src/components/PlayPauseButton.js
- src/components/Slider.js
Checklist:
Closes #XXXXX
Label on the volume control should be "volume" instead of "slider".
I added a step of 5 to the slider which gives the user 21 distinct volume levels to choose from. Giving them 101 seemed excessive, especially for keyboard users.
> fix: volume control accessibility

- .github/workflows/ci.yml
- cypress/integration/home.js
- cypress/integration/play-button.js
- package.json
Checklist:
This PR changes the default localhost port from 3000 to 3001. It's so that the port doesn't collide with the main repo's server port (I was running both repos at the same time and got a funny issue where the /learn client was sending me to code radio rather than logging me in).
> fix: change default port to 3001
